# Generated by Django 4.0.3 on 2022-03-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.TextField(max_length=1000)),
                ('isbn', models.CharField(max_length=13)),
                ('pags', models.IntegerField(default=0)),
                ('año', models.IntegerField(default=1970)),
            ],
            options={
                'db_table': 'libro',
                'ordering': ['titulo'],
            },
        ),
    ]
